// TAGS
export const TAG_SEARCH = 'TAG_SEARCH';
export const TAG_PARSE_ONKEYDOWN = 'TAG_PARSE_ONKEYDOWN';
export const TAG_PARSE_ONKEYUP = 'TAG_PARSE_ONKEYUP';
export const TAG_SEARCH_REMOVE = 'TAG_SEARCH_REMOVE';
export const TAG_SEARCH_ADD = 'TAG_SEARCH_ADD';
export const TAG_SEARCH_DELETE = 'TAG_SEARCH_DELETE';

// BLOCKS
export const BLOCKS_CONFIRMED_LOADING = 'BLOCKS_CONFIRMED_LOADING';
