// Modal Search && Header
export const HDR_TAG_SEARCH = 'HDR_TAG_SEARCH';
export const HDR_TAG_PARSE_ONKEYDOWN = 'HDR_TAG_PARSE_ONKEYDOWN';
export const HDR_TAG_PARSE_ONKEYUP = 'HDR_TAG_PARSE_ONKEYUP';
export const MS_TAG_SEARCH_DELETE = 'MS_TAG_SEARCH_DELETE';
export const HDR_TAG_PARSE_ONBUTTON = 'HDR_TAG_PARSE_ONBUTTON';
export const HDR_TAG_PARSE_DATE = 'HDR_TAG_PARSE_DATE';
export const HDR_TAG_CLEANER = 'HDR_TAG_CLEANER';

// Gallery
export const GLR_GET_CARDS = 'GLR_GET_CARDS';
export const GLR_CARD_LOAD = 'GLR_CARD_LOAD';
export const GLR_CARD_NEWLOAD = 'GLR_CARD_NEWLOAD';
export const GLR_SEARCH_CARDS = 'GLR_SEARCH_CARDS';
export const GLR_SEARCH_SET = 'GLR_SEARCH_SET';

// Upload card
export const UC_TAG_PARSE = 'UC_TAG_PARSE';
export const UC_TAG_DELETE = 'UC_TAG_DELETE';
export const UC_TEXTAREA = 'UC_TEXTAREA';
export const UC_FILEUPLOAD = 'UC_FILEUPLOAD';
export const UC_FILEIMAGEDLETE = 'UC_FILEIMAGEDLETE';
export const UC_TAG_KEYUP = 'UC_TAG_KEYUP';
export const UC_CARD_CLEANER = 'UC_CARD_CLEANER';

// Firebase
export const FB_AUTH_LOGIN = 'FB_AUTH_LOGIN';

// Profile
export const PR_USER_INFO = 'PR_USER_INFO';
export const PR_USER_CARDS = 'PR_USER_CARDS';
export const PR_CARDS_LOAD = 'PR_CARDS_LOAD';
export const PR_CARDS_NEWLOAD = 'PR_CARDS_NEWLOAD';

// Card
export const CA_CARD_INFO = 'CA_CARD_INFO';
export const CA_CARD_LOAD = 'CA_CARD_LOAD';
export const CA_SET_LIKE = 'CA_SET_LIKE';
export const CA_GET_ISLIKED = 'CA_GET_ISLIKED';
export const CA_CARD_DELETE = 'CA_CARD_DELETE';
export const CA_CARD_TEXTAREA = 'CA_CARD_TEXTAREA';
export const CA_CARD_COMMENTS = 'CA_CARD_COMMENTS';
export const CA_CARD_COMMENT_DELETE = 'CA_CARD_COMMENT_DELETE';
export const CA_CARD_COMMENTS_LOAD = 'CA_CARD_COMMENTS_LOAD';
export const CA_CARD_COMMENTS_SEND = 'CA_CARD_COMMENTS_SEND';
