// HDR - HEADER
// MS - MODAL SEARCH
export const HDR_TAG_SEARCH = 'HDR_TAG_SEARCH';
export const HDR_TAG_PARSE_ONKEYDOWN = 'HDR_TAG_PARSE_ONKEYDOWN';
export const HDR_TAG_PARSE_ONKEYUP = 'HDR_TAG_PARSE_ONKEYUP';
export const MS_TAG_SEARCH_DELETE = 'MS_TAG_SEARCH_DELETE';
export const MS_TAG_SEARCH_REMOVE = 'MS_TAG_SEARCH_REMOVE';
export const MS_TAG_SEARCH_ADD = 'MS_TAG_SEARCH_ADD';

// GLR - GALLERY
export const GLR_CARD_LOAD = 'GLR_CARD_LOAD';

// uploadFile

export const UF_TAG_PARSE = 'UF_TAG_PARSE';
export const UF_TAG_DELETE = 'UF_TAG_DELETE';
export const UF_TEXTAREA = 'UF_TEXTAREA';
